version: '3'

services:
    djangoweb:
      image: baraka215/baraka_docker_aws-django
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "80:8000"
      environment:
       - POSTGRES_DB=baraka_docker_aws_db
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=${PG_password}
       - POSTGRES_HOST=${RDS_host}
